# ----------------- Settings -----------------

language: en_us               # Languages available by default: en_us.yml, de_de.yml, fr_fr.yml
xp-formula: "100 + x^1.8"     # x is the current level of the player
max-level: -1                 # Set to -1 to disable Max level
default-level-colour: "f"     # Colour Code of default level colour
enable-placeholder-api: true  # Available PAPI-Placeholders: %jlevel_level%, %jlevel_xp%, %jlevel_required%
check-updates: true

rewards:
  monster-kill: 2
  achievement: 10
  player-kill: 5

# --------------- Level Config ---------------

level-rewards:
  1:
    commands:                 # Available Placeholders: %player%
      - "give %player% diamond 1"
      - "give %player% dirt 64"
    text:
      - "&3one Diamond"
      - "&e64 Dirt"
    colour: "c"               # Level colour given at this level (c = Red), not required!

# --------------------------------------------

config-version: 2 # DO NOT CHANGE